name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      pat:
        description: 'ChatBlogr Access Token'
        required: true
        type: string
      site_name:
        description: 'Site Name'
        required: false
        type: string
      image_url:
        description: 'Base Image URL for Social Media'
        required: false
        type: string
      environment:
        description: 'Deployment Environment (production or preview)'
        required: false
        type: string
        default: 'production'
      vercel_org_id:
        description: 'Vercel Organization ID'
        required: true
        type: string
      vercel_project_id:
        description: 'Vercel Project ID'
        required: true
        type: string
      vercel_token:
        description: 'Vercel Token'
        required: true
        type: string
      
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate images
        run: npm run resize
        env:
          IMAGE_URL: ${{ github.event.inputs.image_url }}

      - name: Update manifest
        run: npm run manifest
        env:
          SITE_NAME: ${{ github.event.inputs.site_name }}

      - name: Build
        run: npm run build
        env:
          CHATBLOGR_PAT: ${{ github.event.inputs.pat }}

      - name: Install Vercel CLI
        run: npm install --save-dev vercel@latest

      - name: Deploy to Vercel
        id: deploy
        run: |
          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            npx vercel deploy --prod --token=${{ github.event.inputs.vercel_token }}
          else
            npx vercel deploy --token=${{ github.event.inputs.vercel_token }}
          fi
        env:
          VERCEL_ORG_ID: ${{ github.event.inputs.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ github.event.inputs.vercel_project_id }}

      - name: Output Deployment URL
        run: echo "Deployment URL: ${{ steps.deploy.outputs.url }}"
